parserOptions:
  ecmaVersion: 2018

env:
  es6: true
  node: true

extends: 'htmlacademy/node'
rules:
  {
    'no-unused-expressions': 0,
    'object-curly-spacing': 0,
    'strict': 0,
    'quotes': 0,
    'indent': 0,
  }
